export const ADD_ITEM: string = "ADD_ITEM"
export const REMOVE_ITEM:string = "REMOVE_ITEM"
export const REMOVE_ALL_ITEMS:string = "REMOVE_ALL_ITEMS"
export const INCREASE_QUANTITY:string = "INCREASE_QUANTITY"
export const DECREASE_QUANTITY:string = "DECREASE_QUANTITY"
export const UPDATE_QUANTITY:string = "UPDATE_QUANTITY"