export const FETCH_ACCOUNT_REQUEST:string = 'FETCH_ACCOUNT_REQUEST'
export const FETCH_ACCOUNT_SUCCESS:string = 'FETCH_USER_REQUEST'
export const FETCH_ACCOUNT_FAILURE:string = 'FETCH_USER_FAILURE'

export const LOGIN_REQUEST:string = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS:string = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE:string = 'LOGIN_FAILURE'

export const REGISTER_REQUEST:string = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS:string = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE:string = 'REGISTER_FAILURE'

export const IS_AUTHENTICATED_FAILURE:string = 'IS_AUTHENTICATED'

export const LOGOUT:string = 'LOGOUT'