version: "3.9"
services:

  backend:
    restart: on-failure
    image: backend
    build:
      context: .
    ports:
      - "3001:3001"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    command: 
      bash -c "cd backend && npm run start"

  authentication:
    restart: on-failure
    image: authentication
    build:
      context: .
    ports:
      - "4000:4000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    command: 
      bash -c "cd backend && npm run auth"

  frontend:
    image: frontend
    build:
      context: .
    ports:
      - "3000:3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    command: 
      "npm start"