version: "3.9"
services:

  database:
    container_name: mysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.22
    networks:
      - backend
      - authentication
    environment:
      MYSQL_DATABASE: bike_erp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOSTNAME: 127.0.0.1
      MYSQL_ROOT_PASSWORD: root
    
    ports:
      - "3306:3306"

  backend:
    depends_on: 
      - database
    restart: on-failure
    image: backend
    build:
      context: .
    ports:
      - "3001:3001"
    networks:
      - backend
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - MYSQL_HOSTNAME=127.0.0.1
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bike_erp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    command: 
      bash -c "cd backend && npm run start"

  authentication:
    restart: on-failure
    image: authentication
    build:
      context: .
    ports:
      - "4000:4000"
    networks:
      - authentication
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - MYSQL_HOSTNAME=127.0.0.1
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bike_erp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    command: 
      bash -c "cd backend && npm run auth"

  frontend:
    image: frontend
    build:
      context: .
    ports:
      - "3000:3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    command: 
      "npm start"

networks: 
  backend:
    driver: bridge
  authentication:
    driver: bridge